export const styles = {
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#f2f2f2",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
    alignItems: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    color: "#333",
    marginBottom: 20
  },
  fieldContainer: {
    marginVertical: 15,
    padding: 15,
    backgroundColor: "#fff",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    width: 300,
    alignItems: "center",
    flexDirection: "row",
  },
  inputWrapper: {
    width: 250,
    marginVertical: 10,
  },
  inputContainer: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: "70%",
  },
  label: {
    fontSize: 16,
    color: "#000",
    marginRight: 10,
    marginBottom: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc", 
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: "100%",
    color: "#333"
  },
  picker: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    width: 150, 
    height: 30,
  },
};
